# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


https://stackoverflow.com/questions/27890735/difference-between-listnumpy-array-and-numpy-array-tolist

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [4]:

a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[7 0 6 9 9 1]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [5]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[2 8 0 5]
 [1 9 4 5]
 [1 5 1 6]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [6]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[5 6]
  [0 0]
  [9 1]]

 [[7 6]
  [3 3]
  [6 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [7]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[2, 9, 5, 9, 8, 0]
[2, 9, 5, 9, 8, 0]


In [8]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[2, 8, 0, 6], [0, 1, 1, 7], [9, 8, 1, 1]]
[array([2, 8, 0, 6]), array([0, 1, 1, 7]), array([9, 8, 1, 1])]


In [9]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[3, 9], [7, 4], [8, 9]], [[8, 8], [7, 7], [9, 1]]]
[array([[3, 9],
       [7, 4],
       [8, 9]]), array([[8, 8],
       [7, 7],
       [9, 1]])]


In [11]:
def tolist(iterable):
  if type(iterable) != np.ndarray:
    return iterable
  newlist = []
  for obj in iterable:
    newlist.append(tolist(obj))
  return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[2, 9, 5, 9, 8, 0]
[[2, 8, 0, 6], [0, 1, 1, 7], [9, 8, 1, 1]]
[[[3, 9], [7, 4], [8, 9]], [[8, 8], [7, 7], [9, 1]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
